POST http://localhost:3000/users/bilal71612@gmail.com
Content-Type: application/json

{
    "label": "test",
    "image": "test",
    "ingredients": {
        "i1": "test",
        "i2": "test"
    }
}

###

POST http://localhost:5000/users/bilal71612@gmail.com
Content-Type: application/json

{
    "label": "test8",
    "image": "test2",
    "ingredients": ["test1", "test2"]
}

###

GET http://localhost:5000/users/bilal71612@gmail.com

###

DELETE http://localhost:5000/users/bilal71612@gmail.com/recipes/659ca29045e8ae2ceb256820
